// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Switch based on environment
    final isDev = EnvironmentConfig.currentEnvironment == Environment.dev;
    
    if (kIsWeb) {
      return isDev ? devWeb : prodWeb;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isDev ? devAndroid : prodAndroid;
      case TargetPlatform.iOS:
        return isDev ? devIos : prodIos;
      case TargetPlatform.macOS:
        return isDev ? devMacos : prodMacos;
      case TargetPlatform.windows:
        return isDev ? devWindows : prodWindows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============ DEVELOPMENT FIREBASE OPTIONS (dev-language-firebase) ============
  
  static const FirebaseOptions devWeb = FirebaseOptions(
    apiKey: 'AIzaSyAWi_onvrMzEodLYQH2a9eH4f8Hk_ml8B8',
    appId: '1:1002258199347:web:b2cb8271222c8a63b3c446',
    messagingSenderId: '1002258199347',
    projectId: 'dev-language-firebase',
    authDomain: 'dev-language-firebase.firebaseapp.com',
    storageBucket: 'dev-language-firebase.firebasestorage.app',
    measurementId: 'G-E50KYVXQ4N',
  );

  static const FirebaseOptions devAndroid = FirebaseOptions(
    apiKey: 'AIzaSyAWi_onvrMzEodLYQH2a9eH4f8Hk_ml8B8',
    appId: '1:1002258199347:android:dev_app_id',
    messagingSenderId: '1002258199347',
    projectId: 'dev-language-firebase',
    storageBucket: 'dev-language-firebase.firebasestorage.app',
  );

  static const FirebaseOptions devIos = FirebaseOptions(
    apiKey: 'AIzaSyAWi_onvrMzEodLYQH2a9eH4f8Hk_ml8B8',
    appId: '1:1002258199347:ios:dev_app_id',
    messagingSenderId: '1002258199347',
    projectId: 'dev-language-firebase',
    storageBucket: 'dev-language-firebase.firebasestorage.app',
    iosBundleId: 'com.ira.flutterapp',
  );

  static const FirebaseOptions devMacos = FirebaseOptions(
    apiKey: 'AIzaSyAWi_onvrMzEodLYQH2a9eH4f8Hk_ml8B8',
    appId: '1:1002258199347:ios:dev_app_id',
    messagingSenderId: '1002258199347',
    projectId: 'dev-language-firebase',
    storageBucket: 'dev-language-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseMockSkel',
  );

  static const FirebaseOptions devWindows = FirebaseOptions(
    apiKey: 'AIzaSyAWi_onvrMzEodLYQH2a9eH4f8Hk_ml8B8',
    appId: '1:1002258199347:web:dev_app_id',
    messagingSenderId: '1002258199347',
    projectId: 'dev-language-firebase',
    authDomain: 'dev-language-firebase.firebaseapp.com',
    storageBucket: 'dev-language-firebase.firebasestorage.app',
    measurementId: 'G-E50KYVXQ4N',
  );

  // ============ PRODUCTION FIREBASE OPTIONS (language-firebase-d5667) ============

  static const FirebaseOptions prodWeb = FirebaseOptions(
    apiKey: 'AIzaSyAGoSyly_M8e2-PFed3VZS_qiFRrVq0Wrc',
    appId: '1:713216071550:web:740ac951ea808d09fd852f',
    messagingSenderId: '713216071550',
    projectId: 'language-firebase-d5667',
    authDomain: 'language-firebase-d5667.firebaseapp.com',
    storageBucket: 'language-firebase-d5667.firebasestorage.app',
    measurementId: 'G-4QQWLGHR1S',
  );

  static const FirebaseOptions prodAndroid = FirebaseOptions(
    apiKey: 'AIzaSyDY45kxMNDiAfyZf1f3iH4IjyXeNHewTBc',
    appId: '1:713216071550:android:c4c821ce31bd2a51fd852f',
    messagingSenderId: '713216071550',
    projectId: 'language-firebase-d5667',
    storageBucket: 'language-firebase-d5667.firebasestorage.app',
  );

  static const FirebaseOptions prodIos = FirebaseOptions(
    apiKey: 'AIzaSyBw0KIwUnNNik2uCgo2BkRpos5f9YZeq9w',
    appId: '1:713216071550:ios:4c78a71f809fdccefd852f',
    messagingSenderId: '713216071550',
    projectId: 'language-firebase-d5667',
    storageBucket: 'language-firebase-d5667.firebasestorage.app',
    iosBundleId: 'com.ira.flutterapp',
  );

  static const FirebaseOptions prodMacos = FirebaseOptions(
    apiKey: 'AIzaSyBw0KIwUnNNik2uCgo2BkRpos5f9YZeq9w',
    appId: '1:713216071550:ios:d59ea233e09a5554fd852f',
    messagingSenderId: '713216071550',
    projectId: 'language-firebase-d5667',
    storageBucket: 'language-firebase-d5667.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseMockSkel',
  );

  static const FirebaseOptions prodWindows = FirebaseOptions(
    apiKey: 'AIzaSyAGoSyly_M8e2-PFed3VZS_qiFRrVq0Wrc',
    appId: '1:713216071550:web:1ee1ff7f1ba1db55fd852f',
    messagingSenderId: '713216071550',
    projectId: 'language-firebase-d5667',
    authDomain: 'language-firebase-d5667.firebaseapp.com',
    storageBucket: 'language-firebase-d5667.firebasestorage.app',
    measurementId: 'G-EZB9LRPJ2L',
  );
}
